spring:
  application:
    name: demo
    issue:
      max-allowed-books: 3

  datasource:
    url: jdbc:postgresql://localhost:5432/service_book
    username: postgres
    password: qqq
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: update
    database: postgresql
