spring:
  application:
    name: demo
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/service_book
    username: postgres
    password: qqq
    driverClassName: org.postgresql.Driver